package com.titan.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.titan.gyslfh.backalarm.BackAlarmModel;
import com.titan.model.TrackPoint;

import com.titan.data.greendao.BackAlarmModelDao;
import com.titan.data.greendao.TrackPointDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig backAlarmModelDaoConfig;
    private final DaoConfig trackPointDaoConfig;

    private final BackAlarmModelDao backAlarmModelDao;
    private final TrackPointDao trackPointDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        backAlarmModelDaoConfig = daoConfigMap.get(BackAlarmModelDao.class).clone();
        backAlarmModelDaoConfig.initIdentityScope(type);

        trackPointDaoConfig = daoConfigMap.get(TrackPointDao.class).clone();
        trackPointDaoConfig.initIdentityScope(type);

        backAlarmModelDao = new BackAlarmModelDao(backAlarmModelDaoConfig, this);
        trackPointDao = new TrackPointDao(trackPointDaoConfig, this);

        registerDao(BackAlarmModel.class, backAlarmModelDao);
        registerDao(TrackPoint.class, trackPointDao);
    }
    
    public void clear() {
        backAlarmModelDaoConfig.clearIdentityScope();
        trackPointDaoConfig.clearIdentityScope();
    }

    public BackAlarmModelDao getBackAlarmModelDao() {
        return backAlarmModelDao;
    }

    public TrackPointDao getTrackPointDao() {
        return trackPointDao;
    }

}
